### ISSUE TITLE
strange pipeline view bug

### ISSUE THREAD

**Issue by mbway** [Simulizer/Simulizer#15]
Symptoms: see attached screenshot

To reproduce:
1. open simulizer
2. load `snake-03-fixed.s`
3. run
4. layouts > pipeline layout

(note: stopping the simulation and running again will crash so badly that the exception dialog can't stay open because the crash brings everything down!)
update: the crash still logs the exception to stdout. The stack trace is useless (no user code, only javafx internals) but the exception is:
`java.lang.InternalError: Unrecognized PGCanvas token: 67` (not just 67, also 65, -34)

also another exception, again the stack trace is useless:
```
java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at com.sun.javafx.sg.prism.GrowableDataBuffer.append(GrowableDataBuffer.java:298)
	at com.sun.javafx.sg.prism.NGCanvas.updateRendering(NGCanvas.java:1541)
	at javafx.scene.canvas.Canvas.impl_updatePeer(Canvas.java:257)
	at javafx.scene.Node.impl_syncPeer(Node.java:503)
	at javafx.scene.Scene$ScenePulseListener.synchronizeSceneNodes(Scene.java:2290)
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2419)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:347)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:374)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$346(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$450(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:745)
```

and also another exception:

```
Thread:  JavaFX Application Thread
At:      2016-09-19 18:52:45.255
Cause:   null
Message: "null"

java.lang.NullPointerException
	at javafx.scene.Scene$ScenePulseListener.synchronizeSceneNodes(Scene.java:2289)
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2419)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:347)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:374)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$346(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication.enterNestedEventLoopImpl(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication._enterNestedEventLoop(GtkApplication.java:211)
	at com.sun.glass.ui.Application.enterNestedEventLoop(Application.java:511)
	at com.sun.glass.ui.EventLoop.enter(EventLoop.java:107)
	at com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(QuantumToolkit.java:583)
	at javafx.stage.Stage.showAndWait(Stage.java:474)
	at javafx.scene.control.HeavyweightDialog.showAndWait(HeavyweightDialog.java:162)
	at javafx.scene.control.Dialog.showAndWait(Dialog.java:341)
	at simulizer.utils.UIUtils.lambda$showExceptionDialog$3(UIUtils.java:252)
	at com.sun.javafx.application.PlatformImpl.lambda$null$117(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$118(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$450(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:745)
```

![bug](https://cloud.githubusercontent.com/assets/4923501/18642869/4e5c1ae4-7e9a-11e6-96f8-b24c3bc90ecd.png)

**Comment by MichaelOultram** [comment]
`Unrecognized PGCanvas token` is normally to do with trying to change a canvas when not on the JavaFX Application Thread. I'll have a go at trying to fix that, and hopefully it'll fix the weird upside-downess. Sadly I can't reproduce the screenshot, but can get the exceptions.

**Comment by MichaelOultram** [comment]
@mbway I've pushed a commit which should solve this issue (the exceptions are gone for me at least). If it also solved the upside-downess you experience then could you please close this issue.

**Comment by mbway** [comment]
I no longer have any issues with this
