### ISSUE TITLE
Running snake pipelined skips the start screen

### ISSUE THREAD

**Issue by MichaelOultram** [Simulizer/Simulizer#18]
Probably related to a deeper problem with CPU/Clock as mentions in #12

**Comment by mbway** [comment]
ooh, that is interesting (hopefully there isn't a massive problem with the simulation at this late stage). Will take a look at that. Probably tomorrow.

**Comment by mbway** [comment]
snake no longer even runs with pipelining. get this exception
```
Thread:  Executor(Message-Manager): Thread(2)
At:      2016-09-25 16:46:00.091
Cause:   null
Message: "null"

java.lang.NullPointerException
	at simulizer.ui.windows.Registers$RegisterListener.processRegisterChangedMessage(Registers.java:240)
	at simulizer.simulation.messages.SimulationListener.delegateMessage(SimulationListener.java:25)
	at simulizer.simulation.messages.MessageManager$MessageTask.run(MessageManager.java:114)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Thread:  CPU-Thread
At:      2016-09-25 16:46:01.927
Cause:   null
Message: "null"

java.lang.NullPointerException
	at simulizer.simulation.cpu.components.CPUPipeline.needToBubble(CPUPipeline.java:171)
	at simulizer.simulation.cpu.components.CPUPipeline.runSingleCycle(CPUPipeline.java:232)
	at simulizer.simulation.cpu.components.CPU.runProgram(CPU.java:500)
	at simulizer.simulation.cpu.components.CPUPipeline.runProgram(CPUPipeline.java:312)
	at simulizer.ui.WindowManager$1.call(WindowManager.java:284)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```
@charlie1329 ??
is this to do with the HI and LO registers

**Comment by charlie1329** [comment]
having just taken a look, snake is running pipe-lined for me, but as per another issue, the start screen isn't showing, and also the key presses aren't registering. It isn't giving me exceptions though.

**Comment by mbway** [comment]
I think the exceptions were about inserting bubbles after LO and HI accesses. I think it was fixed a while ago. the skipping start screen is still an issue though

**Comment by mbway** [comment]
also note that HI and LO need read-after-write hazards and maybe other stuff...
