### ISSUE TITLE
exception running fibonacci code

### ISSUE THREAD

**Issue by mbway** [Simulizer/Simulizer#19]
```
Thread:  Executor(Continuous-Checking): Thread(0)
At:      2016-09-23 12:49:14.245
Cause:   null
Message: "Not on FX application thread; currentThread = Executor(Continuous-Checking): Thread(0)"

java.lang.IllegalStateException: Not on FX application thread; currentThread = Executor(Continuous-Checking): Thread(0)
	at simulizer.utils.UIUtils.assertFXThread(UIUtils.java:51)
	at simulizer.utils.SafeJSObject.call(SafeJSObject.java:35)
	at simulizer.ui.windows.Editor.loadCurrentFile(Editor.java:374)
	at simulizer.ui.components.CurrentFile.tryGetEditor(CurrentFile.java:106)
	at simulizer.ui.components.CurrentFile.loadFileWithoutPrompt(CurrentFile.java:281)
	at simulizer.ui.components.CurrentFile.getCurrentText(CurrentFile.java:131)
	at simulizer.ui.components.CurrentFile.lambda$startContinuousChecking$6(CurrentFile.java:337)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```
	# compiled using GCC with optimisation level 0
	.data
input:
	.ascii	"enter value: �"
rec:
	.ascii	"recursive fibonacci of �"
it:
	.ascii	"iterative fibonacci of �"
js:
	.ascii	"javascript fibonacci of �"
eq:
	.ascii	" = �"
nl:
	.byte	10
	.text
fibRec:
	addiu	$sp,$sp,-40
	sw	$ra,36($sp)
	sw	$fp,32($sp)
	sw	$16,28($sp)
	move	$fp,$sp
	sw	$4,40($fp)
	lw	$2,40($fp)
	# <hazard>
	slti $2,$2,2
	beq	$2,$0,LBL_2
	lw	$2,40($fp)
	b	LBL_3
LBL_2:
	lw	$2,40($fp)
	# <hazard>
	addiu	$2,$2,-1
	move	$4,$2
	jal	fibRec
	move	$16,$2
	lw	$2,40($fp)
	# <hazard>
	addiu	$2,$2,-2
	move	$4,$2
	jal	fibRec
	addu	$2,$16,$2
LBL_3:
	move	$sp,$fp
	lw	$ra,36($sp)
	lw	$fp,32($sp)
	lw	$16,28($sp)
	addiu	$sp,$sp,40
	j	$ra
fibIt:
	addiu	$sp,$sp,-32
	sw	$fp,28($sp)
	move	$fp,$sp
	sw	$4,32($fp)
	lw	$2,32($fp)
	# <hazard>
	slti $2,$2,2
	beq	$2,$0,LBL_5
	lw	$2,32($fp)
	b	LBL_6
LBL_5:
	sw	$0,8($fp)
	li	$2,1			# 0x1
	sw	$2,12($fp)
	li	$2,2			# 0x2
	sw	$2,20($fp)
LBL_8:
	lw	$3,20($fp)
	lw	$2,32($fp)
	# <hazard>
	slt	$2,$2,$3
	bne	$2,$0,LBL_7
	lw	$3,8($fp)
	lw	$2,12($fp)
	# <hazard>
	addu	$2,$3,$2
	sw	$2,16($fp)
	lw	$2,12($fp)
	# <hazard>
	sw	$2,8($fp)
	lw	$2,16($fp)
	# <hazard>
	sw	$2,12($fp)
	lw	$2,20($fp)
	# <hazard>
	addiu	$2,$2,1
	sw	$2,20($fp)
	b	LBL_8
LBL_7:
	lw	$2,16($fp)
LBL_6:
	move	$sp,$fp
	lw	$fp,28($sp)
	addiu	$sp,$sp,32
	j	$ra
	nop # @{ function fibJs(x) { }@
	nop # @{   if(x <= 1) return x; }@
	nop # @{   return fibJs(x-1) + fibJs(x-2); }@
	nop # @{ } }@
main:
	addiu	$sp,$sp,-40
	sw	$ra,36($sp)
	sw	$fp,32($sp)
	move	$fp,$sp
	# get input
	la	$3,input
	li	$v0, 4 # print string
	move	$a0, $3
	syscall
	li	$v0, 5 # read int
	syscall
	move	$3, $v0
	sw	$3,24($fp)
	# recursive implementation
	la	$3,rec
	li	$v0, 4 # print string
	move	$a0, $3
	syscall
	lw	$3,24($fp)
	# <hazard>
	li	$v0, 1 # print int
	move	$a0, $3
	syscall
	la	$3,eq
	li	$v0, 1 # print int
	move	$a0, $3
	syscall
	lw	$4,24($fp)
	jal	fibRec
	move	$3,$2
	li	$v0, 1 # print int
	move	$a0, $3
	syscall
	# iterative implementation
	la	$3,it
	li	$v0, 4 # print string
	move	$a0, $3
	syscall
	lw	$3,24($fp)
	# <hazard>
	li	$v0, 1 # print int
	move	$a0, $3
	syscall
	la	$3,eq
	li	$v0, 1 # print int
	move	$a0, $3
	syscall
	lw	$4,24($fp)
	jal	fibIt
	move	$3,$2
	li	$v0, 1 # print int
	move	$a0, $3
	syscall
	# javascript implementation
	la	$3,js
	li	$v0, 4 # print string
	move	$a0, $3
	syscall
	lw	$3,24($fp)
	# <hazard>
	li	$v0, 1 # print int
	move	$a0, $3
	syscall
	la	$3,eq
	li	$v0, 1 # print int
	move	$a0, $3
	syscall
	lw	$2,24($fp)
	# <hazard>
	nop # @{ var js_x = $2.get(); }@
	nop # @{ $2.set(fibJs(js_x)); }@
	sw	$2,28($fp)
	lw	$3,28($fp)
	# <hazard>
	li	$v0, 1 # print int
	move	$a0, $3
	syscall
	li	$v0, 10 # exit
	syscall
	move	$2,$0
	move	$sp,$fp
	lw	$ra,36($sp)
	lw	$fp,32($sp)
	addiu	$sp,$sp,40
	j	$ra

```

**Comment by mbway** [comment]
this issue contains the program that I was running at the time, but in fact the bug was to do with:
1. open a file
3. make an external change from another text editor and save
4. run the program

which would attempt to set the editor text to the externally modified version from not a JavaFX thread.

In solving this issue I also came across another bug where making a change in simulizer and externally then running crashes for a similar reason.
