### ISSUE TITLE
exception playing snake game with registers window

### ISSUE THREAD

**Issue by mbway** [Simulizer/Simulizer#29]
```
Thread:  Executor(Message-Manager): Thread(2)
At:      2016-09-25 15:05:51.990
Cause:   null
Message: "null"

java.lang.NullPointerException
	at simulizer.ui.windows.Registers$RegisterListener.processRegisterChangedMessage(Registers.java:226)
	at simulizer.simulation.messages.SimulationListener.delegateMessage(SimulationListener.java:25)
	at simulizer.simulation.messages.MessageManager$MessageTask.run(MessageManager.java:114)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by MichaelOultram** [comment]
The registers are receiving a `RegisterChangedMessage` with a null register (therefore outside of my control). I could suppress the error but it wouldn't "fix" it

**Comment by mbway** [comment]
are they the HI and LO regsiters?
