### ISSUE TITLE
TypeErrpr on test entry

### ISSUE THREAD

**Issue by driainstyles** [Simulizer/Simulizer#43]
Hello chaps,

I'm having a go with simulizer and have encountered an issue that happens whenever I enter a character into the editor. The trace is below. This is under windows 7 running Java SE 8u102

Regards,
Iain

Thread:  JavaFX Application Thread
At:      2016-10-06 18:24:11.513
Cause:   null
Message: "TypeError: undefined is not an object (evaluating 'ps.size')"

netscape.javascript.JSException: TypeError: undefined is not an object (evaluating 'ps.size')
    at com.sun.webkit.dom.JSObject.fwkMakeException(JSObject.java:137)
    at com.sun.webkit.dom.JSObject.callImpl(Native Method)
    at com.sun.webkit.dom.JSObject.call(JSObject.java:106)
    at simulizer.utils.SafeJSObject.call(SafeJSObject.java:36)
    at simulizer.ui.windows.Editor.setProblems(Editor.java:375)
    at simulizer.ui.components.CurrentFile.lambda$null$5(CurrentFile.java:367)
    at simulizer.ui.components.CurrentFile.lambda$tryGetEditor$1(CurrentFile.java:113)
    at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
    at java.lang.Thread.run(Unknown Source)

**Comment by mbway** [comment]
I have tried running Simulizer on Windows 7 with JRE 8u102 and could not recreate the issue. I have potentially fixed the issue by changing how the editor problems are sent to javascript to be displayed. Could you run this patched version of Simulizer from a terminal to see whether error messages, specifically "javascript alert: editor problems === undefined" are printed out (it should no longer crash regardless)

[Simulizer-0.3.zip](https://github.com/Simulizer/Simulizer/files/516083/Simulizer-0.3.zip)

if fixed: by entering nonsense into the editor you should see this when hovering over the x in the gutter:
![error](https://cloud.githubusercontent.com/assets/4923501/19189423/da89e192-8c8f-11e6-8fef-a03b3a4a7f23.png)

**Comment by driainstyles** [comment]
Having tried it on another windows machine (I mainly use linux), it seems
more like to be a problem with my windows laptop, which is the only machine
on which I've seen this. I'll try the patch early next week.
Regards,
Iain

**Comment by mbway** [comment]
The issue was apparently due to the Java environment and not Simulizer itsself.
